class ReasonCodes:
    GAME_START = "GAME_START"
    WEALTH_GATE_FAIL = "WEALTH_GATE_FAIL"
    POWER_PRESSURE_SUCCESS = "POWER_PRESSURE_SUCCESS"
    EMOTIONAL_INFLUENCE_SUCCESS = "EMOTIONAL_INFLUENCE_SUCCESS"
    TACTICAL_OBSERVATION = "TACTICAL_OBSERVATION"
